

subroutine energy


! ******************************************************
! ***   FIND DENSITY AND CURRENT IN PHYSICAL SPACE   ***
! ******************************************************
!
! This subroutine integrates over all phase space
! to the energy.  This quantity is defined as:
!
!            /
! Energy  =  | (p**2/2 + phi_ext(r) + L0**2/(2 r**2) + phi_self(r)/2 ) f dr dp
!            /
!
! The self-gravity potential carries a factor 1/2. Summing phi_self over
! particles counts the interaction of every pair twice, once from each side;
! the energy of a self-gravitating system is (1/2) Int rho phi_self. Without
! the 1/2 the sum is not conserved: it changes by (1/2) Delta W_self whenever
! the mass is redistributed, an error of relative size ~a0 that no refinement
! of the discretization removes. The external background and the centrifugal
! term are not generated by the particles and take no factor.

! Include modules.

  use parameters
  use arrays
  use functions
  use utils
! Declare variables.

  implicit none

  integer i
  real(8) :: smallpi,factor

  smallpi = acos(-1.0d0)


! Zero Angular Momentum
  if (Lfix == 0.0d0) then

     factor = 1.0d0

! Include Angular Momentum
  else

     factor = 8.D0*smallpi**2*Lfix*drc*dpc

  endif  

  total_energy = 0.0D0
  kinetic = 0.D0
  potential = 0.D0

  !$OMP PARALLEL DO SCHEDULE(GUIDED) REDUCTION (+:kinetic,potential,total_energy)
  do i=1,Npart
    kinetic   = kinetic + 0.5D0*p_part(i)**2*f(i)
    potential = potential + (pot_part(i) - 0.5D0*potself_part(i))*f(i)
    total_energy = total_energy &
                 + (0.5D0*p_part(i)**2 + pot_part(i) - 0.5D0*potself_part(i))*f(i)
  end do
  !$OMP END PARALLEL DO

  kinetic   = factor * kinetic
  potential = factor * potential
  total_energy    = factor * total_energy

end subroutine energy
